### ISSUE TITLE
Skyrim Unbound Reborn - Whiterun thane compatibility

### ISSUE THREAD

**Issue by azraerl** [mlthelama/ShowStats#12]
Due to how SUR works, Show Stats show player as thane of Whiterun.

Could you please add an option to pick different condition for this one? Here's what exactly SUR changes:
> Conditions on completing or stage of MQ104 "Dragon Rising", which are usually used to check if the player is a thane of Whiterun, are always true with Skyrim Unbound, due to MQ104 being technically completed at the start.
> 
> With Skyrim Unbound Reborn, the condition is different, and the same as the vanilla condition on becoming a thane after the Whiterun siege on stormcloak side: you just need to check if the stage 25 of Favor253 quest is done, in xEdit it looks so: Subject.GetStageDone(Favor253 "Thane of Whiterun" [QUST:000A2C9E], 025) = 1.

-> https://www.nexusmods.com/skyrimspecialedition/articles/1489

**Comment by mlthelama** [comment]
added to 0.0.6 (non beta)
