### ISSUE TITLE
ShowStats not working in AE

### ISSUE THREAD

**Issue by eleroy5** [mlthelama/ShowStats#14]
I have Show Stats AE v 0.0.9
I have this in my skse64.log
          checking plugin ShowStats.dll
          plugin ShowStats.dll (00000000  00000000) no version data 0 (handle 0)
Any idea why it's not loading?

**Comment by mlthelama** [comment]
with the newest version of AE? Not yet but I can retest it, just need to update the game

**Comment by mlthelama** [comment]
i will re up a new version on github and nexus

**Comment by mlthelama** [comment]
[Here](https://github.com/mlthelama/ShowStats/releases/tag/0.0.9-AE)
or
[Nexus](https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=250141&nmm=1&game_id=1704)

**Comment by mlthelama** [comment]
Tested with newest version of Skyrim 

`SKSE64 runtime: initialize (version = 2.1.4 01061560 01D7F455E261FF4C, os = 6.2 (9200))
imagebase = 00007FF7E5720000
reloc mgr imagebase = 00007FF7E5720000
config path = G:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\SKSE\skse.ini
plugin directory = G:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\SKSE\Plugins\
scanning plugin directory G:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\SKSE\Plugins\
checking plugin ShowStats.dll
loading plugin "ShowStats"
registering plugin listener for SKSE at 1 of 3
plugin ShowStats.dll (00000001 ShowStats 84000000) loaded correctly (handle 1)
dispatch message (0) to plugin listeners
sending message type 0 to plugin 1
dispatched message.
dispatch message (1) to plugin listeners
sending message type 1 to plugin 1
dispatched message.
init complete
hooked dinput
dispatch message (6) to plugin listeners
sending message type 6 to plugin 1
dispatched message.
`
