### ISSUE TITLE
Crash with the latest version that uses SKSE, doesnt happen with older ones or when i disable the mod. Crash log mentions it in the registers.

### ISSUE THREAD

**Issue by VishVadeva50** [mlthelama/ShowStats#7]
FrameworkName: NetScriptFramework
FrameworkVersion: 14
FrameworkArchitecture: x64
GameLibrary: SkyrimSE
GameLibraryVersion: 18
ApplicationName: SkyrimSE.exe
ApplicationVersion: 1.5.97.0
VersionInfo: Successfully loaded
Time: 17 Oct 2021 03:21:18.778

Possible relevant objects (3)
{
  [ 166]    ShadowSceneNode(Name: `shadow scene node`)
  [ 171]    BSMultiBoundNode(Name: null)
  [ 173]    NiNode(Name: null)
}

Probable callstack
{
  [0]   0x7FF7B168CBF2     (SkyrimSE.exe+ECCBF2)          unk_ECCBA0+52
  [1]   0x7FF92A55CB6B     (ShowStats.dll+4CB6B)          
  [2]   0x7FF7B07C0000     (SkyrimSE.exe+0)               
  [3]   0xB1F5F3F6A0                                      
  [4]   0xB1F5F3F6A0                                      
  [5]   0xB1F5F3F6B0                                      
  [6]   0x222B9612000                                     
  [7]   0x7FF7B168CC85     (SkyrimSE.exe+ECCC85)          unk_ECCBA0+E5
  [8]   0x7FF92A5635FE     (ShowStats.dll+535FE)          
  [9]   0x7FF7B07C0000     (SkyrimSE.exe+0)               
  [10]  0xB1F5F3F740                                      
}

Registers
{
  AX:       0x7FF7B168CBA0     (SkyrimSE.exe+ECCBA0) (void*)
  BX:       0x7FF7B07C0000     (SkyrimSE.exe+0) (char*) "MZ?"
  CX:       0x0                (NULL)
  DX:       0x0                (NULL)
  SI:       0x0                (NULL)
  DI:       0x0                (NULL)
  BP:       0xB1F5F3F678       (void*)
  SP:       0xB1F5F3F5C0       (void*)
  IP:       0x7FF7B168CBF2     (SkyrimSE.exe+ECCBF2) (void*)
  R8:       0x7FF92A5EBAA8     (ShowStats.dll+DBAA8) (char*) "autoSize"
  R9:       0xB1F5F3F678       (void*)
  R10:      0x1398C            (u32):[80268]
  R11:      0x2209BB00000      (void*)
  R12:      0xB1F5F3F710       (void*)
  R13:      0x0                (NULL)
  R14:      0x7FF92A5EBAA8     (ShowStats.dll+DBAA8) (char*) "autoSize"

**Comment by mlthelama** [comment]
strange then lets see, but thanks for reporting

**Comment by VishVadeva50** [comment]
Forgot to mention, this happens while typing in the prompt text box the game gives when creating a character or when using AdditemMenu search for example

**Comment by mlthelama** [comment]
thanks, then i can try to reproduce it. i did some changes for gfxlog, i will revert them and then we will see

**Comment by mlthelama** [comment]
[ShowStats.zip](https://github.com/mlthelama/ShowStats/files/7358600/ShowStats.zip)

i tried to make a fix (build without fomod), if you could test it, it would be nice

**Comment by mlthelama** [comment]
awesome, then i will put it on nexus soon
